#!/usr/bin/env python3
"""Prune dangling doc references from versioned sidebars.

A snapshot pairs a release's docs/ with its sidebars.js from the SAME mapped
commit. Occasionally that commit is a transient state where sidebars.js already
references a doc that wasn't added until a later commit (or was renamed). Docusaurus
rejects such sidebars hard ("these sidebar document ids do not exist"). This pass
removes references (doc/ref items and category doc-links) to ids absent from the
version's snapshot, dropping categories left empty. Navigation for that version
loses only the already-missing entry.

Run after generation; idempotent.
"""
import glob
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VDOCS = os.path.join(REPO, "versioned_docs")
VSIDEBARS = os.path.join(REPO, "versioned_sidebars")
FM_ID = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)
ID_LINE = re.compile(r"^\s*id:\s*['\"]?([^'\"\n]+)['\"]?\s*$", re.MULTILINE)


def frontmatter_id(path):
    try:
        head = open(path, encoding="utf-8").read(4000)
    except OSError:
        return None
    m = FM_ID.match(head)
    if not m:
        return None
    idm = ID_LINE.search(m.group(1))
    return idm.group(1).strip() if idm else None


def valid_doc_ids(version_dir):
    ids = set()
    for ext in ("md", "mdx"):
        for f in glob.glob(os.path.join(version_dir, "**", f"*.{ext}"), recursive=True):
            rel = os.path.relpath(f, version_dir)
            rel = re.sub(r"\.(md|mdx)$", "", rel).replace(os.sep, "/")
            fid = frontmatter_id(f)
            if fid:
                parts = rel.split("/")
                parts[-1] = fid
                rel = "/".join(parts)
            ids.add(rel)
    return ids


def item_id(item):
    if not isinstance(item, dict):
        return None
    if item.get("type") in ("doc", "ref"):
        return item.get("id")
    return None


def prune(items, valid, stats):
    out = []
    for item in items:
        if isinstance(item, str):
            # shorthand for a doc id
            if item in valid:
                out.append(item)
            else:
                stats["removed"] += 1
            continue
        t = item.get("type")
        if t in ("doc", "ref"):
            if item.get("id") in valid:
                out.append(item)
            else:
                stats["removed"] += 1
        elif t == "category":
            link = item.get("link")
            if (
                isinstance(link, dict)
                and link.get("type") == "doc"
                and link.get("id") not in valid
            ):
                item = {k: v for k, v in item.items() if k != "link"}
                stats["removed"] += 1
            item["items"] = prune(item.get("items", []), valid, stats)
            # keep category only if it still leads somewhere
            if item.get("items") or item.get("link"):
                out.append(item)
            else:
                stats["empty_categories"] += 1
        else:
            out.append(item)  # link / html / autogenerated etc.
    return out


def main():
    sidebar_files = sorted(glob.glob(os.path.join(VSIDEBARS, "version-*-sidebars.json")))
    total = {"removed": 0, "empty_categories": 0, "files_changed": 0}
    for sf in sidebar_files:
        version = re.search(r"version-(.+)-sidebars\.json$", os.path.basename(sf)).group(1)
        vdir = os.path.join(VDOCS, f"version-{version}")
        if not os.path.isdir(vdir):
            continue
        valid = valid_doc_ids(vdir)
        sidebars = json.load(open(sf))
        stats = {"removed": 0, "empty_categories": 0}
        for name in list(sidebars.keys()):
            sidebars[name] = prune(sidebars[name], valid, stats)
        if stats["removed"] or stats["empty_categories"]:
            json.dump(sidebars, open(sf, "w"), indent=2)
            open(sf, "a").write("\n")
            total["files_changed"] += 1
            total["removed"] += stats["removed"]
            total["empty_categories"] += stats["empty_categories"]
            print(f"  {version}: pruned {stats['removed']} dangling ref(s), "
                  f"{stats['empty_categories']} empty categor(y/ies)")
    print(f"[sanitize-sidebars] changed {total['files_changed']} sidebar file(s); "
          f"removed {total['removed']} dangling ref(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
